version: "3.8"

services:
  db:
    image: postgres:14
    container_name: postgres_escolas
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: escolas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_escolas
    restart: always
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      DB_HOST: db  # nome do serviço do postgres no docker-compose
      DB_PORT: 5432
      DB_NAME: escolas
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      - db
    volumes:
      - ./:/app
      - /app/node_modules

volumes:
  postgres_data:
